# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20170704_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
